### ISSUE TITLE
Error when executing the script

### ISSUE THREAD

**Issue by darkyy92** [shbedev/jamf-recovery-lock#5]
I hope it's okay to ask here?

I did all in the readme file (configured the URL, created the user, wrote all in the auth file.
Then installed python3 + requests and launched a Command Prompt (Windows).
Last, I set the filter to one test machine (called "99").

`cd` to the Github directory (cloned with Github Desktop) and then executed the script (main.py).

Then I get this error:

```
C:\Users\darky\OneDrive\Desktop\GitHub\jamf-recovery-lock>python3 main.py
Traceback (most recent call last):
  File "C:\Users\darky\OneDrive\Desktop\GitHub\jamf-recovery-lock\main.py", line 2, in <module>
    from computers import get_arm64, get_mgmt_id
  File "C:\Users\darky\OneDrive\Desktop\GitHub\jamf-recovery-lock\computers.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

<img width="558" alt="cmd_Ro4uVySRR2" src="https://github.com/shbedev/jamf-recovery-lock/assets/85100340/42561418-ed77-4b94-9a9a-207f097ff90f">

**Comment by shbedev** [comment]
Hi, please try the next command to install `requests` for python 3:

```
python3 -m pip install requests
```
